### ISSUE TITLE
Add check for system installed ogre-next

### ISSUE THREAD

**Issue by srmainwaring** [gazebo-release/gazebo_ogre_next_vendor#4]
Similar to https://github.com/gazebo-release/gz_dartsim_vendor/issues/4

Add a check for the system installed version of ogre-next before calling ament_vendor. For example on macOS the appropriate ogre-next libraries are available from brew:

```bash
$ brew info ogre2.3  
==> osrf/simulation/ogre2.3: stable 2.3.1, HEAD
Scene-oriented 3D engine written in c++
https://www.ogre3d.org/
Installed
/opt/homebrew/Cellar/ogre2.3/2.3.1_2 (860 files, 16.6MB) *
  Built from source on 2024-03-04 at 12:23:52
From: https://github.com/osrf/homebrew-simulation/blob/HEAD/Formula/ogre2.3.rb
License: MIT
==> Dependencies
Build: cmake ✔
Required: doxygen ✔, freeimage ✔, freetype ✔, libx11 ✔, libzzip ✔, rapidjson ✔, tbb ✔
==> Options
--HEAD
	Install HEAD version
```

A suggested change (with debug messages) in this branch: https://github.com/srmainwaring/gz_ogre_next_vendor/tree/rolling-macos. 

The change introduces a dependency on gz-cmake(3). Using the `gz-cmake-vendor` version does not seem to work, which is why `gz-cmake3` has been hardcoded. This would need to be resolved before adopting.

**Comment by oysstu** [comment]
Same thing on archlinux. It's better to leverage the distro package instead of having to maintain and compile another source installation.
